# Generated by Django 4.2.1 on 2023-05-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'any'), (2, 'java'), (3, 'c++')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
