# Generated by Django 4.2.1 on 2023-05-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton_main', '0003_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.AddField(
            model_name='task',
            name='test',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
