# Generated by Django 4.2.1 on 2023-05-16 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackaton_main', '0004_delete_snippet_task_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('code', models.TextField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackaton_main.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='membertask',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='membertask',
            name='task_id',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='MemberTask',
        ),
    ]
