# Generated by Django 4.2.1 on 2023-05-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton_main', '0005_usertask_remove_membertask_member_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='test',
        ),
        migrations.AddField(
            model_name='usertask',
            name='language',
            field=models.PositiveSmallIntegerField(choices=[(1, 'java'), (2, 'c++')], default=2),
        ),
    ]
